#!/bin/bash
if [ ! -f  temp.txt ]; then
       touch temp.txt
       echo 1
       echo 1 > temp.txt

else
	cat temp.txt | while read line
    do
	    echo $(expr $line + 1)
	    echo $(expr $line + 1) > temp.txt
    done

    
fi

